### ISSUE TITLE
[Not an issue] GRBL ported to ESP32

### ISSUE THREAD

**Issue by keyz182** [simon-jouet/ESP32Controller#2]
Not sure if there's a forum, or somewhere for discussion, so posting here - 
https://hackaday.com/2018/07/26/grbl-ported-to-the-esp32/
Worth keeping an eye on.

**Comment by simon-jouet** [comment]
hey @keyz182 thanks, yeah I saw this as well over lunch :) I posted a reply to hackaday just in case some people are interested. Regarding the forum no there is nothing for now, if people are interested I could set something up, or maybe start a thread/category on https://discuss.toms3d.org
